name: npm test
on: 
  workflow_dispatch:
               
jobs:
  job1-run-npm-install:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v5
      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 'lts/*'
      - name: Install npm
        shell: bash
        run: |
          npm install
  job2-run-npm-test:
    needs: job1-run-npm-install
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v5
      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 'lts/*'
      - name: run test
        shell: bash
        run: |
          npm install
          npm test

      