name: npm test with matrixes
on: 
  workflow_dispatch:

jobs:
  run-npm-install:
    strategy:
      matrix:
        os: ["ubuntu-latest", "ubuntu-22.04"]
        node-version: ["20", "lts/*"]
        include:
          - os: "ubuntu-latest"
            node-version: "18"

    runs-on: ${{ matrix.os }}
    steps:
        - name: checkout
          uses: actions/checkout@v5
        - name : setup node
          uses: actions/setup-node@v6
          with:
            node-version: ${{ matrix.node-version }}
        - name: run install
          shell: bash
          run: |
            npm install
            npm test