name: build docker
on: 
  pull_request:
  push:
    branches: 
      - main

jobs:
  run-npm-install:
    runs-on: ubuntu-latest
    steps:
        - name: checkout
          uses: actions/checkout@v5
        - name : setup node
          uses: actions/setup-node@v6
          with:
            node-version: 'lts/*'
        - name: run install
          shell: bash
          run: |
            npm install
            npm test
        - name: build docker image
          shell: bash
          run: |
            docker build -t ${{ github.sha }} .